package com.toolshare.toolshare.controller;

import com.toolshare.toolshare.entity.User;
import com.toolshare.toolshare.repository.UserRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/user") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    //
    // POST-REQUESTS
    //

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String last_name, @RequestParam int age) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setLastName(last_name);
        n.setAge(age);
        userRepository.save(n);

        return "Saved";
    }

    @PostMapping(path="/delete")
    public @ResponseBody  String deleteUserByID(@RequestParam int id) {

        userRepository.deleteById(id);

        return "Deleted";
    }

    //
    // GET-REQUESTS
    //


    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path="/age")
    public @ResponseBody Iterable<User> getUserbyName(@RequestParam int age) {
        return userRepository.findUsersByAge(age);
    }
}